### ISSUE TITLE
Letter Ɩ have diacritic   ̄  but not ~ 

### ISSUE THREAD

**Issue by matsbla** [globalbility/keyman-togo#10]
I'm able to write ɩ̄ but not ɩ̃
In fact ɩ̄ is not on the diacritic combinations overview page.
However I can see that the diacritic used on the overview page is wrong, so I corrected it here:
https://github.com/globalbility/keyman-togo/wiki/Togolese-diacritic-combinations/_compare/26af0d733e0d65114114d9ed290622f9d3f30504...42b136a28141d1c211003e848a5395025b42b50e

**Comment by matsbla** [comment]
Using KeyMan10 on windows 10 Home and word 2016

**Comment by andjc** [comment]
Latest build ready for testing.

**Comment by matsbla** [comment]
Good, this looks like working now!
