### ISSUE TITLE
Only provide keyboards for documented languages

### ISSUE THREAD

**Issue by matsbla** [globalbility/keyman-togo#7]
The file now provide about 35 keyboards. However many of these languages don't have an orthography. I think we, for the start, should limit the languages to those we do have information about:
https://github.com/globalbility/keyman-togo/wiki/Extended-Latin-requirements-by-language
Other languages can simply use the French (Togo) as all letters will be available there anyway.

![screenshot from 2018-08-13 22-50-40](https://user-images.githubusercontent.com/4965568/44057458-961164ba-9f4b-11e8-8f19-a4ab3fc7780f.png)

**Comment by andjc** [comment]
Which languages should be in the list?

**Comment by matsbla** [comment]
Only those in this list which we have documented which extended letters are needed:
https://github.com/globalbility/keyman-togo/wiki/Extended-Latin-requirements-by-language

These languages: Aja, Anii, Ewe, Fon, Fulfulde, Ife, Ikposo, Kabiye, Lama, Lukpa, Mina, Miyobe, Moba, Nawdm, Ngangam, Ntcham, Tem

These languages are also in the list and should be removed:
Adangbe, Adele, Igbo, Akaselem, Akebu, Anufo, Ginyanga, Bissa, Delo, Gen, Gourmanchéma, Northern Nago, Konkomba, Bago-Kusuntu, Kusaal, Mampruil, Mossi, Mbelime, Ditammari, Biali, Western Xwla Gbe

Can you check the commit I did? Is this enough to update the list?

**Comment by andjc** [comment]
There is no commit. Have you pushed it?

You need to update language lists in kps file in the keyboard_info file.

Bump version numbers in kmn, kps files. 

Recompile keyboard and recompile package

**Comment by matsbla** [comment]
I created a new branch for it, the commit is here:
https://github.com/globalbility/keyman-togo/commit/2f510231ce449395a690a4c8a57d77348c3127d0

**Comment by matsbla** [comment]
Thanks!

**Comment by andjc** [comment]
Changes merged.
